### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by P-S-S-M** [open-radiation-sources/parametric-plasma-source#6]
Hello,

I have an error when pip installing the parametric-plasma-source (attached output). I have a fresh install of Linux and have followed the OpenMC workshop instructions for OpenMC/DAGMC, below. I am obviously reluctant to start playing about with modules in-case I break the OpenMC/DAGMC install.

https://github.com/ukaea/openmc_workshop/blob/test_conda_install_script/install_scripts/install_conda_cadquery_openmc_dagmc_trelis_plugin.sh

Could you advice on fixing the Pip install?

Thanks,
Sam

**Comment by shimwell** [comment]
Thanks for reporting, I'm not sure if the output got attached to that last message, but it could be helpful for solving this

While we look into this problem I wonder if this works for you

```bash
git clone https://github.com/open-radiation-sources/parametric-plasma-source.git
cd parametric-plasma-source
pip install .
```

While looking around the repo I noticed the main branch was a bit out of date with develop so have made a PR #5

**Comment by P-S-S-M** [comment]
Please see the error below, sorry for not attaching correctly previously: 
[plasma_source_error.txt](https://github.com/open-radiation-sources/parametric-plasma-source/files/5453279/plasma_source_error.txt)

**Comment by shimwell** [comment]
Looks like the pip upload doesn't contain everything
extract from the error file
```"/tmp/pip-install-4v9d7vdy/parametric-plasma-source" does not appear to contain CMakeLists.txt.```

**Comment by P-S-S-M** [comment]
Cloning the directory as you suggested installs correctly, thanks.

**Comment by DanShort12** [comment]
Could be that we need to add `cmake` as an install dependency. A better solution would be to put `cmake` into the `requirements.txt` but use the `manylinux` build to generate a wheel that doesn't need to be compiled on the user's machine.

**Comment by shimwell** [comment]
Looks like that merging worked @DanShort12  

the Test PyPi upload worked https://test.pypi.org/project/parametric-plasma-source/#history

the github actions worked
https://github.com/open-radiation-sources/parametric-plasma-source/actions/runs/345529430

**Comment by shimwell** [comment]
Therefore I suggest we merge from development to main and that should update the main pypi package

**Comment by DanShort12** [comment]
Yep, sounds good to me. That should hopefully fix this error.

**Comment by shimwell** [comment]
Looks like the merge to main didn't quite update the pypi package :-(

https://pypi.org/project/parametric-plasma-source/#history

**Comment by shimwell** [comment]
The creation of a github release triggered the github action which updated the pypi release and solved this problem. Feel free to reopen if this reoccurs. Closing for now
