### ISSUE TITLE
CI doesn't run on develop branch

### ISSUE THREAD

**Issue by DanShort12** [open-radiation-sources/parametric-plasma-source#8]
The python.yml CI file does not use the new branch names. These should be updated so that CI is triggered on a push or pull request to main or develop.

**Comment by shimwell** [comment]
Thanks for adding the correct branch names in #9

**Comment by shimwell** [comment]
For anyone reading this it appears that some gitactions don't trigger whe a PR is made from a fork

**Comment by DanShort12** [comment]
Closing as this has been done.
